#  COURSERA_CAPSTONE PROJECT

In [42]:
#importing the libraries
import pandas as pd
import numpy as np

## Loading data into dataframe from url

In [67]:
url="https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M"
df=pd.read_html(url, header=0)[0]

df.head(10)

  Postal code           Borough                                  Neighborhood
0         M1A      Not assigned                                           NaN
1         M2A      Not assigned                                           NaN
2         M3A        North York                                     Parkwoods
3         M4A        North York                              Victoria Village
4         M5A  Downtown Toronto                    Regent Park / Harbourfront
5         M6A        North York             Lawrence Manor / Lawrence Heights
6         M7A  Downtown Toronto  Queen's Park / Ontario Provincial Government
7         M8A      Not assigned                                           NaN
8         M9A         Etobicoke                              Islington Avenue
9         M1B       Scarborough                               Malvern / Rouge

## Dropping the rows with not assigned Borough

In [68]:
df.drop(df[df.Borough == "Not assigned"].index, inplace=True)

## Final Dataset

In [79]:
df.reset_index(drop=True,inplace=True)
df["Neighborhood"]=df["Neighborhood"].str.replace("/",",")
df.sort_values("Postal code", axis = 0, ascending = True, inplace = True,) 
df.head(20)

   Postal code      Borough                                       Neighborhood
0          M1B  Scarborough                                    Malvern , Rouge
1          M1C  Scarborough           Rouge Hill , Port Union , Highland Creek
2          M1E  Scarborough                Guildwood , Morningside , West Hill
3          M1G  Scarborough                                             Woburn
4          M1H  Scarborough                                          Cedarbrae
5          M1J  Scarborough                                Scarborough Village
6          M1K  Scarborough      Kennedy Park , Ionview , East Birchmount Park
7          M1L  Scarborough                  Golden Mile , Clairlea , Oakridge
8          M1M  Scarborough  Cliffside , Cliffcrest , Scarborough Village West
9          M1N  Scarborough                       Birch Cliff , Cliffside West
10         M1P  Scarborough  Dorset Park , Wexford Heights , Scarborough To...
11         M1R  Scarborough                                 Wexford , Maryvale
12         M1S  Scarborough                                          Agincourt
13         M1T  Scarborough          Clarks Corners , Tam O'Shanter , Sullivan
14         M1V  Scarborough  Milliken , Agincourt North , Steeles East , L'...
15         M1W  Scarborough                     Steeles West , L'Amoreaux West
16         M1X  Scarborough                                        Upper Rouge
17         M2H   North York                                  Hillcrest Village
18         M2J   North York                     Fairview , Henry Farm , Oriole
19         M2K   North York                                    Bayview Village

In [66]:
df.shape

(103, 3)

## Reading coordinates data into Dataframe and appending it to our df

In [84]:
x=pd.read_csv("Geospatial_Coordinates.csv")

In [83]:
df["Latitude"]=x["Latitude"]
df["Longitude"]=x["Longitude"]
df.head(10)

,Postal code,Borough,Neighborhood,Latitude,Longitude
0,M1B,Scarborough,"Malvern , Rouge",43.806686,-79.194353
1,M1C,Scarborough,"Rouge Hill , Port Union , Highland Creek",43.784535,-79.160497
2,M1E,Scarborough,"Guildwood , Morningside , West Hill",43.763573,-79.188711
3,M1G,Scarborough,Woburn,43.770992,-79.216917
4,M1H,Scarborough,Cedarbrae,43.773136,-79.239476
5,M1J,Scarborough,Scarborough Village,43.744734,-79.239476
6,M1K,Scarborough,"Kennedy Park , Ionview , East Birchmount Park",43.727929,-79.262029
7,M1L,Scarborough,"Golden Mile , Clairlea , Oakridge",43.711112,-79.284577
8,M1M,Scarborough,"Cliffside , Cliffcrest , Scarborough Village West",43.716316,-79.239476
9,M1N,Scarborough,"Birch Cliff , Cliffside West",43.692657,-79.264848